insert into public.vocab_words (sort_order, word, fast_meaning, example_sentence)
values
  (1, 'aberrant', 'departing from what is normal', 'Because the beetle’s markings were aberrant, the biologist rechecked whether it belonged to the same species.'),
  (2, 'abstruse', 'difficult to understand clearly', 'The philosopher’s abstruse argument became easier to follow once the teacher supplied a concrete example.'),
  (3, 'acerbic', 'sharp or biting in tone', 'The critic’s acerbic review praised the cinematography but mocked nearly every line of dialogue.'),
  (4, 'acrimonious', 'bitter and angry in tone', 'The debate grew acrimonious when participants stopped addressing the evidence and began attacking one another.'),
  (5, 'adamant', 'firmly unwilling to change', 'Although the committee suggested revisions, the architect remained adamant that the original design was structurally sound.'),
  (6, 'adroit', 'skillful and clever in handling', 'The moderator’s adroit questions helped turn a scattered discussion into a focused exchange.'),
  (7, 'adulation', 'excessive praise or admiration', 'The novelist distrusted public adulation, arguing that applause could make writers less willing to revise.'),
  (8, 'affable', 'friendly and easy to approach', 'The new principal was affable enough that even nervous freshmen felt comfortable asking questions.'),
  (9, 'alacrity', 'cheerful eagerness to act', 'When volunteers were requested, Maya accepted the difficult assignment with surprising alacrity.'),
  (10, 'alienate', 'cause others to feel estranged', 'The mayor’s dismissive comments threatened to alienate voters who had previously supported her.'),
  (11, 'allay', 'reduce fear or concern', 'The engineer released additional safety data to allay residents’ worries about the bridge.'),
  (12, 'alleviate', 'make a problem less severe', 'The city planted trees along the avenue to alleviate the worst effects of summer heat.'),
  (13, 'ambivalent', 'having mixed or conflicting feelings', 'The historian felt ambivalent about the discovery because it clarified one mystery while raising several others.'),
  (14, 'ameliorate', 'make something bad better', 'The new filtration system helped ameliorate water quality problems in the coastal town.'),
  (15, 'amenable', 'open to persuasion or suggestion', 'The editor was amenable to changing the headline once the reporter explained the ambiguity.'),
  (16, 'amorphous', 'lacking clear shape or structure', 'The group began with an amorphous goal, but weekly meetings gradually produced a detailed plan.'),
  (17, 'anachronistic', 'out of its proper time', 'The film’s anachronistic slang sounded modern even though the story was set in the eighteenth century.'),
  (18, 'ancillary', 'supporting the main purpose', 'The museum’s ancillary programs, including workshops and lectures, deepened visitors’ understanding of the exhibition.'),
  (19, 'anodyne', 'mild and unlikely to offend', 'The candidate gave an anodyne speech that pleased the crowd but revealed little about her policies.'),
  (20, 'anomalous', 'not fitting the usual pattern', 'The anomalous temperature reading led the researchers to inspect the sensor for errors.'),
  (21, 'antagonistic', 'actively opposed or hostile', 'The two theories seemed antagonistic until new evidence showed that both described different stages of the process.'),
  (22, 'antipathy', 'strong dislike or opposition', 'The poet’s antipathy toward industrialization appears repeatedly in his descriptions of crowded factories.'),
  (23, 'antithetical', 'directly opposed in nature', 'A policy that discourages questions is antithetical to the school’s stated commitment to inquiry.'),
  (24, 'apocryphal', 'of doubtful authenticity', 'The apocryphal story about the inventor is entertaining, but no contemporary documents confirm it.'),
  (25, 'appease', 'calm by giving concessions', 'The board revised the proposal to appease critics who feared the project would reduce public access.'),
  (26, 'arbitrary', 'based on no clear reason', 'The cutoff seemed arbitrary because two applicants with nearly identical scores received different decisions.'),
  (27, 'arcane', 'known by only a few', 'The article translated arcane legal terminology into language that ordinary readers could understand.'),
  (28, 'ardent', 'intensely enthusiastic or devoted', 'An ardent supporter of public libraries, Chen argued that they were essential civic institutions.'),
  (29, 'arduous', 'requiring great effort', 'The team’s arduous climb was slowed by loose rock, thin air, and sudden changes in weather.'),
  (30, 'assiduous', 'careful and persistent in effort', 'Through assiduous research, the student found overlooked letters that changed the paper’s argument.'),
  (31, 'astute', 'shrewd and perceptive', 'The economist’s astute observation was that the trend reflected consumer caution, not lack of interest.'),
  (32, 'austere', 'plain, severe, or restrained', 'The chapel’s austere interior contained little decoration, directing attention to the quiet geometry of the space.'),
  (33, 'authoritative', 'reliable and commanding trust', 'The article became authoritative because it synthesized decades of evidence rather than relying on a single study.'),
  (34, 'autonomous', 'self-governing or independent', 'The laboratory designed an autonomous drone that could map forests without constant human control.'),
  (35, 'aversion', 'strong dislike or avoidance', 'His aversion to publicity made him an unusual choice to represent the company at public events.'),
  (36, 'banal', 'so common it is boring', 'The essay’s conclusion felt banal because it repeated a familiar point without adding insight.'),
  (37, 'belie', 'give a false impression of', 'The singer’s calm expression belied the intense preparation behind the performance.'),
  (38, 'bellicose', 'eager for conflict or war', 'The senator’s bellicose rhetoric alarmed diplomats who hoped to preserve negotiations.'),
  (39, 'benign', 'harmless or gently favorable', 'The chemical looked alarming, but tests showed that it was benign in small concentrations.'),
  (40, 'bolster', 'strengthen or support something', 'The newly discovered inscription helped bolster the archaeologist’s interpretation of the site.'),
  (41, 'bombastic', 'overblown and pretentious', 'The mayor’s bombastic speech used grand phrases but offered few specific plans.'),
  (42, 'brevity', 'concise use of words', 'The scientist valued brevity, summarizing a complex experiment in three clear sentences.'),
  (43, 'brusque', 'abrupt in manner or speech', 'The librarian’s brusque reply sounded rude, though she later explained that she was rushing to fix a catalog error.'),
  (44, 'burgeon', 'grow or increase rapidly', 'Interest in urban gardening began to burgeon after the city converted vacant lots into community plots.'),
  (45, 'cacophonous', 'harsh or jarring in sound', 'The market was cacophonous at noon, with vendors calling out prices over the rumble of traffic.'),
  (46, 'candid', 'honest and direct', 'The director’s candid account of the project’s failures made the final success more credible.'),
  (47, 'capricious', 'unpredictable and impulsive', 'Because the river’s course was capricious, farmers hesitated to build too close to its banks.'),
  (48, 'catalyst', 'thing that triggers change', 'The court decision became a catalyst for reforms that had been discussed for years.'),
  (49, 'caustic', 'bitingly critical or sarcastic', 'Her caustic comments made the proposal’s weaknesses obvious, but they also discouraged further discussion.'),
  (50, 'censure', 'officially criticize or condemn', 'The council voted to censure the official for withholding the environmental report.'),
  (51, 'chary', 'cautious and reluctant', 'Having seen similar programs fail, the superintendent was chary of adopting the new software immediately.'),
  (52, 'charlatan', 'fraud pretending to have expertise', 'The pamphlet exposed the supposed healer as a charlatan who sold useless remedies.'),
  (53, 'circumspect', 'careful to avoid risk', 'The diplomat was circumspect in her wording so that neither side would feel publicly insulted.'),
  (54, 'circumvent', 'find a way around', 'The company tried to circumvent the regulation by moving the records to a foreign server.'),
  (55, 'clandestine', 'secret and concealed', 'The activists held clandestine meetings after the government banned public gatherings.'),
  (56, 'coalesce', 'come together into one', 'Separate neighborhood complaints began to coalesce into a citywide movement for safer streets.'),
  (57, 'coerce', 'force by pressure or threats', 'The study excluded responses from participants who felt coerced rather than freely willing to participate.'),
  (58, 'cogent', 'clear, logical, and convincing', 'The lawyer’s cogent summary helped the jury understand why the timeline mattered.'),
  (59, 'commensurate', 'matching in size or degree', 'The punishment was not commensurate with the offense, which had been minor and accidental.'),
  (60, 'complacent', 'too satisfied to improve', 'The company became complacent after years of success and ignored signs that customers wanted change.'),
  (61, 'conciliatory', 'intended to reduce conflict', 'After weeks of dispute, the chair offered a conciliatory proposal that included parts of both plans.'),
  (62, 'conducive', 'helping something happen', 'A quiet room and clear schedule are conducive to the kind of sustained reading the course requires.'),
  (63, 'conjecture', 'guess based on incomplete evidence', 'The archaeologist described her claim as conjecture until additional pottery fragments could be analyzed.'),
  (64, 'consequential', 'having important effects', 'A seemingly small change in the voting rules proved consequential in the final outcome.'),
  (65, 'construe', 'interpret in a particular way', 'Critics construed the artist’s silence as agreement, though she had made no public statement.'),
  (66, 'contentious', 'likely to cause argument', 'The proposal was contentious because it protected wetlands but limited new housing.'),
  (67, 'contemptuous', 'showing scorn or disrespect', 'The review was contemptuous of the sequel, calling it a louder version of a weaker story.'),
  (68, 'contrite', 'sincerely sorry for wrongdoing', 'The student was contrite after realizing that his joke had embarrassed a classmate.'),
  (69, 'convoluted', 'needlessly complex and hard to follow', 'The instructions were so convoluted that even experienced volunteers completed the form incorrectly.'),
  (70, 'copious', 'large in amount or number', 'The historian took copious notes, recording not only dates but also contradictions among sources.'),
  (71, 'corroborate', 'confirm with supporting evidence', 'The satellite images corroborate the sailors’ reports of unusually large ice floes.'),
  (72, 'credulous', 'too ready to believe claims', 'A credulous audience accepted the rumor before anyone checked whether the photograph was genuine.'),
  (73, 'cursory', 'quick and not thorough', 'The inspector’s cursory examination missed the crack that a careful review later revealed.'),
  (74, 'debunk', 'show that a claim is false', 'The article sought to debunk the myth that the invention was created by one person alone.'),
  (75, 'decorum', 'proper behavior or restraint', 'The judge insisted on decorum, reminding the audience that applause was inappropriate in court.'),
  (76, 'deferential', 'showing respectful submission', 'The interviewer was deferential to the scientist but still pressed her on the study’s limitations.'),
  (77, 'deleterious', 'causing significant harm', 'The pesticide had a deleterious effect on nearby streams, reducing insect diversity within months.'),
  (78, 'delineate', 'describe or outline precisely', 'The report delineates the responsibilities of each agency during a public health emergency.'),
  (79, 'denigrate', 'criticize unfairly or belittle', 'The essay denigrates popular fiction without considering why readers value it.'),
  (80, 'deplore', 'strongly disapprove of', 'The editorial did not merely question the policy; it deplored the secrecy with which it was adopted.'),
  (81, 'deride', 'mock or ridicule openly', 'Opponents derided the plan as naive, though later data showed that it reduced congestion.'),
  (82, 'derivative', 'lacking originality; copied', 'The film’s plot felt derivative, borrowing familiar twists from several better thrillers.'),
  (83, 'despondent', 'deeply discouraged or hopeless', 'The failed launch left the team despondent until engineers identified a problem they could fix.'),
  (84, 'desultory', 'lacking focus or consistency', 'His desultory notes jumped from chemistry to music history without explaining the connection.'),
  (85, 'detractor', 'person who criticizes something', 'Even the project’s most persistent detractor admitted that the final design improved the park.'),
  (86, 'didactic', 'intended to teach, sometimes preachy', 'The novel’s didactic passages explain its moral themes so directly that the characters briefly disappear.'),
  (87, 'diffident', 'shy from lack of confidence', 'Although diffident in large groups, the researcher answered technical questions with quiet authority.'),
  (88, 'digress', 'stray from the main point', 'The lecturer began to digress, moving from climate data to a story about his childhood garden.'),
  (89, 'dilatory', 'intended to cause delay', 'The judge rejected the dilatory motion because it seemed designed only to postpone the trial.'),
  (90, 'discerning', 'able to judge carefully', 'A discerning reader notices that the narrator’s cheerful tone masks deep uncertainty.'),
  (91, 'discredit', 'damage trust or credibility', 'The forged footnote helped discredit the entire article, even though many claims were accurate.'),
  (92, 'disparate', 'fundamentally different in kind', 'The study compared disparate communities, from dense coastal cities to isolated mountain towns.'),
  (93, 'dispassionate', 'calm and unbiased', 'The committee requested a dispassionate review rather than a defense of decisions already made.'),
  (94, 'dissemble', 'hide true motives or feelings', 'The ambassador tried to dissemble, but her strained smile revealed disappointment.'),
  (95, 'divisive', 'causing disagreement or conflict', 'The zoning plan became divisive when residents realized it would affect schools differently.'),
  (96, 'dogged', 'persistent despite difficulty', 'Through dogged investigation, the journalist located records that officials had overlooked.'),
  (97, 'dogmatic', 'rigidly certain in opinions', 'The professor disliked dogmatic arguments that treated complex questions as already settled.'),
  (98, 'dubious', 'doubtful or questionable', 'The claim seemed dubious because it rested on a survey of only twelve people.'),
  (99, 'duplicitous', 'deceptive in a two-faced way', 'The emails revealed a duplicitous strategy: praising cooperation publicly while undermining it privately.'),
  (100, 'ebullient', 'cheerful and full of energy', 'The team’s ebullient mood returned when the repaired telescope transmitted its first image.'),
  (101, 'eclectic', 'drawn from many sources', 'The composer’s eclectic style combines jazz rhythms, folk melodies, and electronic textures.'),
  (102, 'efface', 'erase or make less visible', 'The restoration cleaned the mural without effacing the marks that showed its age.'),
  (103, 'efficacious', 'producing the intended effect', 'The new tutoring schedule proved efficacious, especially for students who needed frequent feedback.'),
  (104, 'effusive', 'showing excessive emotion or praise', 'The critic was unusually effusive, calling the small exhibit one of the year’s best.'),
  (105, 'egregious', 'remarkably bad or offensive', 'The report found egregious errors, including misplaced decimal points that changed the results.'),
  (106, 'elide', 'omit or gloss over', 'The textbook elides the controversy, presenting the reform as if everyone had supported it.'),
  (107, 'elusive', 'hard to find or define', 'A clear explanation for the population decline remained elusive despite years of fieldwork.'),
  (108, 'empirical', 'based on observation or evidence', 'The theory was elegant, but it needed empirical support before scientists would accept it.'),
  (109, 'emulate', 'imitate with effort to equal', 'Young architects tried to emulate her use of light without copying her buildings directly.'),
  (110, 'engender', 'cause or give rise to', 'The opaque hiring process engendered suspicion among applicants who expected clear criteria.'),
  (111, 'enervate', 'drain energy or vitality', 'The long meeting seemed to enervate the committee rather than move it toward a decision.'),
  (112, 'enigmatic', 'mysterious and hard to interpret', 'The poet’s final line is enigmatic, inviting several readings without confirming any one of them.'),
  (113, 'ephemeral', 'short-lived or fleeting', 'The desert flowers were ephemeral, blooming for only a few days after the rain.'),
  (114, 'equivocal', 'ambiguous or open to doubt', 'The survey results were equivocal: they showed interest in the plan but no clear support.'),
  (115, 'erudite', 'learned and scholarly', 'The lecturer was erudite, but she explained medieval trade in terms that beginners could follow.'),
  (116, 'eschew', 'deliberately avoid or reject', 'The journalist chose to eschew dramatic language and let the documents speak for themselves.'),
  (117, 'esoteric', 'understood by only specialists', 'The article made an esoteric debate in linguistics accessible to general readers.'),
  (118, 'exacerbate', 'make a problem worse', 'Building on the floodplain could exacerbate the town’s drainage problems during heavy storms.'),
  (119, 'exculpate', 'clear from blame or guilt', 'The security footage helped exculpate the employee accused of taking the documents.'),
  (120, 'exigent', 'requiring immediate attention', 'The power outage created exigent conditions at the hospital, where backup systems had to start at once.'),
  (121, 'expedient', 'practical but not necessarily principled', 'The shortcut was expedient, but it left future engineers with a system no one fully understood.'),
  (122, 'expedite', 'make a process faster', 'The new filing system should expedite permit reviews that once took several months.'),
  (123, 'extant', 'still existing today', 'Only three extant copies of the pamphlet are known, and each differs slightly from the others.'),
  (124, 'extemporaneous', 'done without preparation', 'The mayor’s extemporaneous remarks sounded more sincere than the carefully drafted statement.'),
  (125, 'extol', 'praise with great enthusiasm', 'The essay extols the painter’s bold colors but says little about her weaker compositions.'),
  (126, 'extraneous', 'irrelevant or unnecessary', 'The editor removed extraneous details that distracted from the central argument.'),
  (127, 'extrapolate', 'infer beyond known data', 'Researchers were careful not to extrapolate national trends from a study of one neighborhood.'),
  (128, 'facile', 'too easy or simplistic', 'The article offered a facile explanation for inequality, ignoring the history that shaped it.'),
  (129, 'fallacious', 'based on faulty reasoning', 'The argument was fallacious because it treated correlation as proof of causation.'),
  (130, 'fastidious', 'very attentive to detail', 'The archivist was fastidious, labeling each folder with dates, sources, and condition notes.'),
  (131, 'fatuous', 'foolish and silly', 'The proposal sounded fatuous once someone asked how it would be funded.'),
  (132, 'feasible', 'possible and practical', 'The design is ambitious, but engineers say it is feasible with existing materials.'),
  (133, 'fervent', 'intensely passionate or devoted', 'The activist remained a fervent defender of free public transit even after the bill failed.'),
  (134, 'fickle', 'changing loyalties or interests', 'The fickle market rewarded the product in June and rejected it by September.'),
  (135, 'flippant', 'not showing proper seriousness', 'Her flippant response frustrated researchers who had spent years studying the disease.'),
  (136, 'foment', 'stir up trouble or unrest', 'The pamphlet did not merely describe grievances; it tried to foment resistance.'),
  (137, 'forestall', 'prevent by acting early', 'Officials strengthened the levee to forestall damage from the approaching storm.'),
  (138, 'fortuitous', 'happening by lucky chance', 'A fortuitous meeting at the archive led the historian to a diary she had never seen.'),
  (139, 'fraught', 'filled with difficulty or tension', 'The negotiations were fraught because each concession risked angering supporters at home.'),
  (140, 'frivolous', 'lacking seriousness or value', 'The court dismissed the frivolous complaint, finding no evidence behind its claims.'),
  (141, 'garrulous', 'excessively talkative and rambling', 'The garrulous guide shared so many anecdotes that the tour fell behind schedule.'),
  (142, 'genial', 'warm and pleasantly friendly', 'The scientist’s genial manner made the demanding laboratory feel less intimidating.'),
  (143, 'gratuitous', 'unnecessary and unwarranted', 'The film’s gratuitous violence distracted from what might have been a thoughtful story.'),
  (144, 'gregarious', 'sociable and outgoing', 'The gregarious researcher built a wide network of collaborators across several universities.'),
  (145, 'hackneyed', 'overused and unoriginal', 'The speech relied on hackneyed phrases about progress but avoided specific commitments.'),
  (146, 'harbinger', 'early sign of what follows', 'The first cracked tiles were a harbinger of more serious structural problems.'),
  (147, 'haughty', 'arrogantly superior in manner', 'The nobleman’s haughty tone reveals how little he understands the workers’ complaints.'),
  (148, 'heterodox', 'departing from accepted views', 'Her heterodox interpretation challenged decades of scholarship about the painting.'),
  (149, 'homogeneous', 'uniform or very similar', 'The sample was too homogeneous to support conclusions about a diverse population.'),
  (150, 'hyperbole', 'deliberate exaggeration for effect', 'Calling the delay a catastrophe was hyperbole; the train arrived only ten minutes late.'),
  (151, 'iconoclastic', 'attacking established beliefs', 'The director’s iconoclastic staging angered traditionalists but attracted younger audiences.'),
  (152, 'idiosyncratic', 'peculiar to one person or group', 'The composer’s idiosyncratic notation confused performers until she explained her symbols.'),
  (153, 'immutable', 'unchangeable over time', 'The treaty treated the border as immutable, though rivers and settlements continued to shift.'),
  (154, 'impartial', 'not favoring either side', 'The panel chose an impartial reviewer with no connection to the applicants.'),
  (155, 'impassive', 'showing little emotion', 'The witness remained impassive while describing events that unsettled everyone else.'),
  (156, 'impede', 'slow down or obstruct', 'Fallen trees impeded rescue crews trying to reach the village.'),
  (157, 'imperious', 'domineering and arrogantly commanding', 'The director’s imperious style made assistants afraid to question even obvious mistakes.'),
  (158, 'imperturbable', 'not easily upset or disturbed', 'During the chaotic rehearsal, the conductor remained imperturbable and calmly restarted the movement.'),
  (159, 'impetuous', 'acting rashly or impulsively', 'The senator’s impetuous announcement surprised aides who had planned a more gradual rollout.'),
  (160, 'implicit', 'suggested but not directly stated', 'The contract contained an implicit promise that artists would retain credit for their work.'),
  (161, 'implacable', 'impossible to appease or stop', 'The critic remained implacable, rejecting every revision as too cautious.'),
  (162, 'incendiary', 'likely to provoke conflict', 'The columnist’s incendiary claims drew attention but made compromise more difficult.'),
  (163, 'incisive', 'sharp and clear in thought', 'Her incisive questions exposed assumptions that the report had left unexamined.'),
  (164, 'incongruous', 'not fitting the context', 'The modern glass tower looked incongruous among the town’s stone cottages.'),
  (165, 'incontrovertible', 'impossible to dispute', 'The recording provided incontrovertible evidence that the meeting had taken place.'),
  (166, 'incumbent', 'required as a duty', 'It is incumbent on researchers to explain risks before asking volunteers to participate.'),
  (167, 'indignant', 'angry at unfair treatment', 'Residents were indignant when they learned that the park had been sold without public notice.'),
  (168, 'indolent', 'lazy or avoiding effort', 'The novel portrays the heir as indolent, more interested in comfort than responsibility.'),
  (169, 'ineffable', 'too great for words', 'The choir’s final chord created an ineffable stillness that no review could quite capture.'),
  (170, 'inexorable', 'impossible to stop or prevent', 'The glacier’s inexorable movement reshaped the valley over thousands of years.'),
  (171, 'inimical', 'hostile or harmful to something', 'The invasive plant proved inimical to native grasses, crowding them out within two seasons.'),
  (172, 'innocuous', 'harmless and unlikely to offend', 'The question seemed innocuous, but it revealed a serious gap in the data.'),
  (173, 'inscrutable', 'impossible to understand clearly', 'The judge’s inscrutable expression gave neither side a hint about her decision.'),
  (174, 'insipid', 'dull, bland, and uninteresting', 'The adaptation was visually polished but insipid, lacking the novel’s humor and urgency.'),
  (175, 'insular', 'narrow and isolated in outlook', 'The committee’s insular habits made it slow to notice changes in the broader field.'),
  (176, 'intractable', 'difficult to manage or solve', 'The housing shortage became intractable because each proposed solution faced a different legal barrier.'),
  (177, 'intrepid', 'fearless and determined', 'The intrepid reporter entered the storm zone to document conditions after the evacuation.'),
  (178, 'intrinsic', 'belonging naturally or essentially', 'The artifact’s value was not merely historical; its intrinsic beauty also drew attention.'),
  (179, 'irascible', 'easily angered or irritated', 'The irascible coach shouted at minor mistakes that others barely noticed.'),
  (180, 'irrefutable', 'impossible to prove wrong', 'The DNA results offered irrefutable support for the revised account of the migration.'),
  (181, 'judicious', 'showing wise judgment', 'The editor made judicious cuts, preserving the argument while removing repetition.'),
  (182, 'laconic', 'using very few words', 'His laconic reply, though only one sentence long, ended the debate.'),
  (183, 'latent', 'hidden but capable of emerging', 'The drought revealed latent weaknesses in a water system that had seemed reliable.'),
  (184, 'laudable', 'worthy of praise', 'The school’s goal was laudable, even if its first attempt to achieve it was flawed.'),
  (185, 'leery', 'cautious and distrustful', 'After the misleading advertisement, customers became leery of the company’s claims.'),
  (186, 'lethargic', 'sluggish and low in energy', 'The afternoon heat made the students lethargic until a brief discussion revived the class.'),
  (187, 'lucid', 'clear and easy to understand', 'The guide’s lucid explanation helped visitors grasp the engineering behind the ancient aqueduct.'),
  (188, 'magnanimous', 'generous toward a rival', 'The winner was magnanimous, publicly praising the opponent who had challenged her hardest.'),
  (189, 'malleable', 'easily shaped or influenced', 'The metal is malleable when heated, allowing artisans to form it into delicate patterns.'),
  (190, 'marginalize', 'push to the edge or exclude', 'The policy unintentionally marginalized rural students who lacked reliable internet access.'),
  (191, 'mendacious', 'not truthful or honest', 'The investigation exposed mendacious testimony that had distorted the public record.'),
  (192, 'mercurial', 'changeable and unpredictable', 'The CEO’s mercurial decisions made long-term planning nearly impossible.'),
  (193, 'meticulous', 'extremely careful and precise', 'The botanist’s meticulous drawings captured details that photographs often missed.'),
  (194, 'mitigate', 'make less severe', 'The shade structures helped mitigate heat stress during outdoor events.'),
  (195, 'mollify', 'soothe anger or anxiety', 'The revised schedule mollified parents who had objected to the earlier start time.'),
  (196, 'morose', 'gloomy and withdrawn', 'The usually cheerful narrator becomes morose after realizing that his plan has failed.'),
  (197, 'multifaceted', 'having many aspects', 'The problem is multifaceted, involving transportation, housing, and public health.'),
  (198, 'munificent', 'very generous in giving', 'The foundation’s munificent grant allowed the library to preserve thousands of rare recordings.'),
  (199, 'nascent', 'just beginning to develop', 'The nascent industry attracted investors before clear regulations had been written.'),
  (200, 'nebulous', 'vague and poorly defined', 'The committee endorsed a nebulous goal of improvement but never specified how to measure it.'),
  (201, 'nominal', 'existing in name only', 'The king retained nominal authority, but elected ministers made the important decisions.'),
  (202, 'nuanced', 'showing subtle distinctions', 'The essay offers a nuanced view of technology, noting both its benefits and its costs.'),
  (203, 'obdurate', 'stubbornly refusing to change', 'The landlord remained obdurate even after inspectors confirmed the tenants’ complaints.'),
  (204, 'obfuscate', 'make unclear or confusing', 'The company’s report seemed designed to obfuscate the costs rather than explain them.'),
  (205, 'objective', 'unbiased and fact-based', 'The evaluator tried to remain objective by using the same criteria for every submission.'),
  (206, 'obsequious', 'overly eager to please', 'The assistant’s obsequious praise made the director doubt whether any feedback was sincere.'),
  (207, 'obstinate', 'stubbornly refusing to yield', 'The scientist was obstinate about the hypothesis until new measurements contradicted it.'),
  (208, 'obviate', 'make unnecessary; prevent', 'The online database may obviate the need for researchers to travel to the archive.'),
  (209, 'officious', 'intrusively offering unwanted help', 'The officious clerk rearranged the display despite having no responsibility for it.'),
  (210, 'onerous', 'burdensome and difficult', 'The reporting requirements were so onerous that small organizations struggled to comply.'),
  (211, 'opaque', 'not clear or understandable', 'The agency’s opaque explanation fueled suspicion rather than resolving it.'),
  (212, 'ostensible', 'appearing true but possibly not', 'The ostensible purpose of the meeting was routine planning, but everyone expected a debate.'),
  (213, 'ostentatious', 'showy to impress others', 'The mansion’s ostentatious entrance contrasted with the owner’s claims of modest taste.'),
  (214, 'parochial', 'narrow in outlook or scope', 'The editorial took a parochial view, ignoring how the policy would affect neighboring towns.'),
  (215, 'partisan', 'strongly biased toward one side', 'The report sounded partisan because it dismissed evidence favorable to the opposition.'),
  (216, 'pedantic', 'overly focused on small details', 'The review became pedantic when it spent two paragraphs correcting a minor date format.'),
  (217, 'perfunctory', 'done with minimal care', 'The official gave a perfunctory apology that acknowledged the delay but not its consequences.'),
  (218, 'peripheral', 'less central or important', 'The subplot is peripheral at first, but it later clarifies the hero’s motivation.'),
  (219, 'pernicious', 'harmful in a subtle way', 'The rumor had a pernicious effect, slowly eroding trust within the team.'),
  (220, 'pervasive', 'spread widely throughout something', 'The smell of smoke was pervasive, reaching even rooms far from the kitchen.'),
  (221, 'petulant', 'childishly sulky or irritable', 'The actor’s petulant response to mild criticism surprised reporters at the event.'),
  (222, 'placate', 'calm someone’s anger', 'The company offered refunds to placate customers affected by the outage.'),
  (223, 'plausible', 'seemingly reasonable or believable', 'The explanation was plausible, but the investigator wanted evidence before accepting it.'),
  (224, 'poignant', 'deeply moving with sadness', 'The memoir’s most poignant scene describes a reunion that occurs too late.'),
  (225, 'polemical', 'strongly argumentative or controversial', 'The essay’s polemical tone energized supporters but alienated readers seeking balance.'),
  (226, 'pragmatic', 'practical rather than idealistic', 'The mayor took a pragmatic approach, choosing the plan that could be funded immediately.'),
  (227, 'precarious', 'unsafe or uncertain', 'The village’s food supply remained precarious after storms damaged the only road.'),
  (228, 'precipitous', 'very steep or sudden', 'The company’s precipitous decline surprised analysts who had predicted slow growth.'),
  (229, 'preclude', 'prevent from happening', 'The narrow entrance precludes the use of large equipment during restoration.'),
  (230, 'precocious', 'developed unusually early', 'The precocious pianist composed a short concerto before entering high school.'),
  (231, 'prescient', 'accurately predicting the future', 'The researcher’s prescient warning about data privacy seemed exaggerated until the breach occurred.'),
  (232, 'presumptuous', 'too bold or self-assured', 'It was presumptuous to rewrite the proposal before the committee had even discussed it.'),
  (233, 'pretense', 'false appearance or claim', 'The meeting maintained a pretense of cooperation while both sides prepared to withdraw.'),
  (234, 'prodigious', 'impressively large or great', 'The poet’s prodigious output included plays, essays, and hundreds of letters.'),
  (235, 'prolific', 'producing many works or results', 'The laboratory was prolific, publishing influential findings in several fields each year.'),
  (236, 'proponent', 'person who supports an idea', 'A proponent of open data, Singh argued that public research should be freely accessible.'),
  (237, 'prosaic', 'ordinary and lacking imagination', 'The diary’s prosaic details about meals and weather reveal the texture of daily life.'),
  (238, 'provisional', 'temporary and subject to change', 'The map is provisional until surveyors confirm the boundary markers.'),
  (239, 'prudent', 'careful and sensible', 'The hikers made a prudent decision to turn back before the storm reached the ridge.'),
  (240, 'pugnacious', 'eager to argue or fight', 'The pugnacious columnist treated every disagreement as an invitation to battle.'),
  (241, 'qualified', 'limited or conditional', 'The committee offered qualified support, praising the aim while questioning the budget.'),
  (242, 'quixotic', 'unrealistically idealistic or impractical', 'The plan to restore every abandoned theater in the state was inspiring but quixotic.'),
  (243, 'rancorous', 'full of bitter hostility', 'The election left a rancorous mood that made bipartisan work difficult.'),
  (244, 'rebut', 'answer by proving wrong', 'The scientist used new data to rebut claims that the pattern was random.'),
  (245, 'recalcitrant', 'stubbornly resistant to authority', 'The recalcitrant witness refused to answer even routine questions.'),
  (246, 'reconcile', 'make consistent or harmonious', 'The historian tried to reconcile two accounts that described the same event differently.'),
  (247, 'refute', 'prove a claim false', 'Later experiments refute the assumption that the compound works only at high temperatures.'),
  (248, 'relegate', 'demote to lower importance', 'The new textbook relegates the once-famous battle to a brief footnote.'),
  (249, 'renounce', 'formally give up or reject', 'The philosopher renounced his earlier view after encountering evidence he could not dismiss.'),
  (250, 'repudiate', 'reject as false or wrong', 'The author publicly repudiated the article after learning that its main source was fabricated.'),
  (251, 'rescind', 'officially cancel or withdraw', 'The university agreed to rescind the fee after students showed it had been imposed by mistake.'),
  (252, 'reticent', 'reluctant to speak openly', 'The engineer was reticent about the failure until the investigation was complete.'),
  (253, 'reverent', 'deeply respectful in attitude', 'The documentary takes a reverent approach to its subject, avoiding gossip and speculation.'),
  (254, 'rudimentary', 'basic and undeveloped', 'The shelter had only rudimentary medical supplies, so serious cases were sent elsewhere.'),
  (255, 'salient', 'most noticeable or important', 'The report’s salient finding is that attendance improved when buses arrived more reliably.'),
  (256, 'sanguine', 'optimistic in a difficult situation', 'Despite early setbacks, the coach remained sanguine about the team’s chances.'),
  (257, 'sardonic', 'dryly mocking or cynical', 'The narrator’s sardonic humor exposes the absurdity of the town’s traditions.'),
  (258, 'scrupulous', 'careful and morally exact', 'The auditor was scrupulous, checking even minor transactions for irregularities.'),
  (259, 'scrutinize', 'examine very carefully', 'Reviewers scrutinize each application for evidence that the project can be completed.'),
  (260, 'sedulous', 'diligent and persistent', 'The sedulous assistant cataloged every specimen before the museum reopened.'),
  (261, 'seminal', 'strongly influential and original', 'The paper became seminal because later researchers built entire fields from its method.'),
  (262, 'serendipitous', 'discovered by fortunate accident', 'The cure’s discovery was serendipitous, emerging from an experiment designed for another purpose.'),
  (263, 'skeptical', 'inclined to doubt claims', 'The editor remained skeptical until the reporter produced documents supporting the story.'),
  (264, 'soporific', 'causing sleepiness or drowsiness', 'The lecture’s soporific pace made even an exciting topic seem dull.'),
  (265, 'specious', 'seeming true but actually false', 'The advertisement made a specious claim by comparing prices from different years.'),
  (266, 'sporadic', 'occurring irregularly or occasionally', 'The region received only sporadic rainfall, making farming unreliable.'),
  (267, 'spurious', 'false or not genuine', 'The museum removed the spurious painting after tests showed modern pigments.'),
  (268, 'stalwart', 'loyal and dependable', 'A stalwart defender of the program, Ortiz attended every budget meeting.'),
  (269, 'steadfast', 'firmly loyal or constant', 'The researcher remained steadfast in her commitment to publishing the full results.'),
  (270, 'stymie', 'block or hinder progress', 'Missing records stymied the investigation for months.'),
  (271, 'substantiate', 'support with solid evidence', 'The committee asked the speaker to substantiate the allegation before repeating it publicly.'),
  (272, 'substantive', 'having real importance or substance', 'The revision was substantive, changing the argument rather than merely correcting grammar.'),
  (273, 'succinct', 'brief and clearly expressed', 'The judge’s succinct explanation made a complicated ruling understandable.'),
  (274, 'supercilious', 'arrogantly disdainful or superior', 'The critic’s supercilious tone suggested that popular taste was beneath consideration.'),
  (275, 'superfluous', 'more than is needed', 'The final paragraph was superfluous because the essay had already reached its conclusion.'),
  (276, 'supplant', 'replace or take the place of', 'Digital archives did not supplant libraries, but they changed how many researchers use them.'),
  (277, 'surreptitious', 'done secretly or stealthily', 'The student made a surreptitious recording of the meeting, later raising privacy concerns.'),
  (278, 'tacit', 'understood without being stated', 'There was a tacit agreement that no one would discuss the failed experiment during dinner.'),
  (279, 'taciturn', 'habitually quiet or reserved', 'The taciturn sculptor rarely explained her work, preferring viewers to study it closely.'),
  (280, 'tangential', 'only slightly related', 'The anecdote was interesting but tangential to the essay’s main claim.'),
  (281, 'tantamount', 'equivalent in effect', 'The budget cut was tantamount to canceling the program because no staff would remain.'),
  (282, 'tenable', 'reasonable and defensible', 'The hypothesis is tenable only if the dating of the fossils is accurate.'),
  (283, 'tentative', 'uncertain and not final', 'The committee reached a tentative agreement, pending approval from both departments.'),
  (284, 'tenuous', 'weak or thinly supported', 'The link between the two events is tenuous, based mainly on timing rather than evidence.'),
  (285, 'terse', 'brief and abrupt', 'The director’s terse email announced the delay without explanation.'),
  (286, 'thwart', 'prevent from succeeding', 'Heavy cloud cover thwarted the astronomers’ attempt to observe the eclipse.'),
  (287, 'torpid', 'sluggish and inactive', 'The torpid economy showed little sign of recovery until exports increased.'),
  (288, 'tractable', 'easy to manage or control', 'The revised model made a complex problem tractable enough for students to solve.'),
  (289, 'transient', 'short-lived or temporary', 'The city built shelters for workers whose jobs were transient and seasonal.'),
  (290, 'trenchant', 'sharp, forceful, and clear', 'The essay offers a trenchant critique of policies that reward speed over accuracy.'),
  (291, 'ubiquitous', 'found almost everywhere', 'The once rare device is now ubiquitous in classrooms, offices, and homes.'),
  (292, 'unassuming', 'modest and not showy', 'The unassuming scientist avoided attention despite having led the landmark study.'),
  (293, 'undermine', 'weaken gradually or secretly', 'Inconsistent rules can undermine trust even when leaders intend to be fair.'),
  (294, 'unequivocal', 'completely clear and unambiguous', 'The committee’s conclusion was unequivocal: the bridge was unsafe.'),
  (295, 'unprecedented', 'never having happened before', 'The court faced an unprecedented question about ownership of digital artifacts.'),
  (296, 'untenable', 'not defensible or sustainable', 'The theory became untenable once researchers discovered contradictory evidence.'),
  (297, 'urbane', 'polished and sophisticated', 'The diplomat’s urbane manner helped ease tension during the reception.'),
  (298, 'vacillate', 'waver between choices', 'The board continued to vacillate, delaying a decision until costs rose.'),
  (299, 'vacuous', 'empty of thought or meaning', 'The slogan sounded inspiring but was vacuous without a plan behind it.'),
  (300, 'vehement', 'intense and forceful', 'Residents were vehement in their opposition to closing the neighborhood clinic.'),
  (301, 'venerable', 'respected because of age or history', 'The venerable institution adapted slowly but retained its reputation for rigorous scholarship.'),
  (302, 'veracity', 'truthfulness or accuracy', 'Reporters questioned the veracity of the leaked memo because its source was unknown.'),
  (303, 'verbose', 'using too many words', 'The verbose instructions confused readers who needed a simple sequence of steps.'),
  (304, 'viable', 'able to work successfully', 'The proposal became viable once the city identified a stable funding source.'),
  (305, 'vindicate', 'clear of blame or justify', 'The later discovery vindicated the researcher, whose early claims had been dismissed.'),
  (306, 'vindictive', 'desiring revenge or punishment', 'The manager’s vindictive response to criticism created fear rather than improvement.'),
  (307, 'virulent', 'extremely harmful or hostile', 'The pamphlet’s virulent attacks made civil debate nearly impossible.'),
  (308, 'volatile', 'likely to change suddenly', 'The volatile exchange rate complicated planning for the international project.'),
  (309, 'wary', 'cautious because of possible danger', 'The villagers were wary of promises that sounded generous but lacked written guarantees.'),
  (310, 'whimsical', 'playful or fanciful', 'The illustrator’s whimsical maps included sea monsters, invented islands, and tiny jokes.'),
  (311, 'zealous', 'enthusiastic to an extreme', 'A zealous reformer, Patel accepted slow progress only when it led to lasting change.')
on conflict (word) do update
set
  sort_order = excluded.sort_order,
  fast_meaning = excluded.fast_meaning,
  example_sentence = excluded.example_sentence,
  source = 'sat_300_plus_vocab_dataset';
