create extension if not exists pgcrypto with schema extensions;

do $$
begin
  create type public.study_session_phase as enum ('learn', 'practice', 'complete');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.daily_word_status as enum ('new', 'shaky', 'stable', 'recall_ready');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.question_type as enum ('meaning_recognition', 'reverse_recall', 'sat_usage');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.answer_confidence as enum ('known', 'guessed');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.completion_reason as enum ('mastered', 'question_cap', 'manual');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.user_word_status as enum ('learning', 'weak', 'recall_ready');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.vocab_words (
  id bigint generated by default as identity primary key,
  word text not null,
  fast_meaning text not null,
  example_sentence text not null,
  source text not null default 'sat_300_plus_vocab_dataset',
  sort_order integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vocab_words_word_key unique (word),
  constraint vocab_words_sort_order_key unique (sort_order),
  constraint vocab_words_word_not_blank check (length(btrim(word)) > 0),
  constraint vocab_words_fast_meaning_not_blank check (length(btrim(fast_meaning)) > 0),
  constraint vocab_words_example_sentence_not_blank check (length(btrim(example_sentence)) > 0)
);

create table if not exists public.study_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  study_date date not null,
  phase public.study_session_phase not null default 'learn',
  daily_word_count smallint not null,
  question_cap smallint not null default 45,
  learn_index smallint not null default 0,
  total_questions_answered integer not null default 0,
  completed_at timestamptz,
  completion_reason public.completion_reason,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint study_sessions_user_study_date_key unique (user_id, study_date),
  constraint study_sessions_id_user_id_key unique (id, user_id),
  constraint study_sessions_daily_word_count_check check (daily_word_count between 5 and 7),
  constraint study_sessions_question_cap_check check (question_cap > 0),
  constraint study_sessions_learn_index_check check (learn_index >= 0),
  constraint study_sessions_total_questions_check check (total_questions_answered >= 0),
  constraint study_sessions_completion_check check (
    (phase = 'complete' and completed_at is not null and completion_reason is not null)
    or (phase <> 'complete' and completion_reason is null)
  )
);

create table if not exists public.study_session_words (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  vocab_word_id bigint not null references public.vocab_words(id) on delete restrict,
  position smallint not null,
  status public.daily_word_status not null default 'new',
  satisfied_meaning_recognition boolean not null default false,
  satisfied_reverse_recall boolean not null default false,
  satisfied_sat_usage boolean not null default false,
  correct_count integer not null default 0,
  miss_count integer not null default 0,
  guessed_count integer not null default 0,
  last_question_type public.question_type,
  last_attempted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint study_session_words_session_user_fkey foreign key (session_id, user_id)
    references public.study_sessions(id, user_id) on delete cascade,
  constraint study_session_words_session_vocab_key unique (session_id, vocab_word_id),
  constraint study_session_words_session_position_key unique (session_id, position),
  constraint study_session_words_id_user_id_key unique (id, user_id),
  constraint study_session_words_position_check check (position >= 0),
  constraint study_session_words_counts_check check (
    correct_count >= 0 and miss_count >= 0 and guessed_count >= 0
  )
);

create table if not exists public.study_question_attempts (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null,
  session_word_id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  vocab_word_id bigint not null references public.vocab_words(id) on delete restrict,
  question_type public.question_type not null,
  selected_vocab_word_id bigint not null references public.vocab_words(id) on delete restrict,
  is_correct boolean not null,
  confidence public.answer_confidence,
  created_at timestamptz not null default now(),
  constraint study_question_attempts_session_user_fkey foreign key (session_id, user_id)
    references public.study_sessions(id, user_id) on delete cascade,
  constraint study_question_attempts_session_word_user_fkey foreign key (session_word_id, user_id)
    references public.study_session_words(id, user_id) on delete cascade,
  constraint study_question_attempts_confidence_check check (
    (is_correct = true) or (confidence is null)
  )
);

create table if not exists public.user_word_mastery (
  user_id uuid not null references auth.users(id) on delete cascade,
  vocab_word_id bigint not null references public.vocab_words(id) on delete cascade,
  status public.user_word_status not null default 'learning',
  correct_count integer not null default 0,
  miss_count integer not null default 0,
  guessed_count integer not null default 0,
  last_seen_at timestamptz,
  last_ready_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, vocab_word_id),
  constraint user_word_mastery_counts_check check (
    correct_count >= 0 and miss_count >= 0 and guessed_count >= 0
  )
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_vocab_words_updated_at on public.vocab_words;
create trigger set_vocab_words_updated_at
before update on public.vocab_words
for each row execute function public.set_updated_at();

drop trigger if exists set_study_sessions_updated_at on public.study_sessions;
create trigger set_study_sessions_updated_at
before update on public.study_sessions
for each row execute function public.set_updated_at();

drop trigger if exists set_study_session_words_updated_at on public.study_session_words;
create trigger set_study_session_words_updated_at
before update on public.study_session_words
for each row execute function public.set_updated_at();

drop trigger if exists set_user_word_mastery_updated_at on public.user_word_mastery;
create trigger set_user_word_mastery_updated_at
before update on public.user_word_mastery
for each row execute function public.set_updated_at();

create index if not exists vocab_words_sort_order_idx
  on public.vocab_words (sort_order);

create index if not exists study_sessions_user_date_idx
  on public.study_sessions (user_id, study_date desc);

create index if not exists study_sessions_user_open_idx
  on public.study_sessions (user_id, study_date desc)
  where completed_at is null;

create index if not exists study_session_words_session_status_idx
  on public.study_session_words (session_id, status, position);

create index if not exists study_session_words_user_status_idx
  on public.study_session_words (user_id, status);

create index if not exists study_session_words_vocab_idx
  on public.study_session_words (vocab_word_id);

create index if not exists study_question_attempts_session_created_idx
  on public.study_question_attempts (session_id, created_at desc);

create index if not exists study_question_attempts_user_word_idx
  on public.study_question_attempts (user_id, vocab_word_id, created_at desc);

create index if not exists user_word_mastery_user_status_idx
  on public.user_word_mastery (user_id, status, last_seen_at);

alter table public.vocab_words enable row level security;
alter table public.study_sessions enable row level security;
alter table public.study_session_words enable row level security;
alter table public.study_question_attempts enable row level security;
alter table public.user_word_mastery enable row level security;

drop policy if exists "Authenticated users can read vocab words" on public.vocab_words;
create policy "Authenticated users can read vocab words"
on public.vocab_words
for select
to authenticated
using (true);

drop policy if exists "Users can read own study sessions" on public.study_sessions;
create policy "Users can read own study sessions"
on public.study_sessions
for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Users can insert own study sessions" on public.study_sessions;
create policy "Users can insert own study sessions"
on public.study_sessions
for insert
to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists "Users can update own study sessions" on public.study_sessions;
create policy "Users can update own study sessions"
on public.study_sessions
for update
to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

drop policy if exists "Users can read own session words" on public.study_session_words;
create policy "Users can read own session words"
on public.study_session_words
for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Users can insert own session words" on public.study_session_words;
create policy "Users can insert own session words"
on public.study_session_words
for insert
to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists "Users can update own session words" on public.study_session_words;
create policy "Users can update own session words"
on public.study_session_words
for update
to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

drop policy if exists "Users can read own attempts" on public.study_question_attempts;
create policy "Users can read own attempts"
on public.study_question_attempts
for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Users can insert own attempts" on public.study_question_attempts;
create policy "Users can insert own attempts"
on public.study_question_attempts
for insert
to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists "Users can update own attempts" on public.study_question_attempts;
create policy "Users can update own attempts"
on public.study_question_attempts
for update
to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

drop policy if exists "Users can read own word mastery" on public.user_word_mastery;
create policy "Users can read own word mastery"
on public.user_word_mastery
for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Users can insert own word mastery" on public.user_word_mastery;
create policy "Users can insert own word mastery"
on public.user_word_mastery
for insert
to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists "Users can update own word mastery" on public.user_word_mastery;
create policy "Users can update own word mastery"
on public.user_word_mastery
for update
to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));
