alter table public.vocab_words
  add column if not exists roots text[] not null default '{}',
  add column if not exists prefixes text[] not null default '{}',
  add column if not exists suffixes text[] not null default '{}',
  add column if not exists etymology text,
  add column if not exists confusable_words text[] not null default '{}',
  add column if not exists image_path text,
  add column if not exists image_alt text,
  add column if not exists image_attribution text,
  add column if not exists image_source_url text;

alter table public.study_question_attempts
  add column if not exists shown_at timestamptz,
  add column if not exists answered_at timestamptz,
  add column if not exists response_time_ms integer,
  add column if not exists timed_mode boolean not null default false,
  add column if not exists timed_out boolean not null default false,
  add column if not exists scheduler_rating smallint,
  add constraint study_question_attempts_response_time_check
    check (response_time_ms is null or response_time_ms between 0 and 3600000),
  add constraint study_question_attempts_scheduler_rating_check
    check (scheduler_rating is null or scheduler_rating between 1 and 4);

alter table public.study_session_words
  add column if not exists scheduler_rating_applied boolean not null default false;

alter table public.study_question_attempts
  drop constraint if exists study_question_attempts_answer_shape_check;
alter table public.study_question_attempts
  add constraint study_question_attempts_answer_shape_check check (
    (timed_out and selected_vocab_word_id is null and typed_answer is null)
    or
    (not timed_out and answer_mode = 'multiple_choice' and selected_vocab_word_id is not null and typed_answer is null)
    or
    (not timed_out and answer_mode = 'typed' and selected_vocab_word_id is null and typed_answer is not null)
  );

create table if not exists public.user_study_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  timed_mode boolean not null default false,
  timer_seconds smallint not null default 30,
  speech_rate real not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_study_preferences_timer_check check (timer_seconds between 10 and 120),
  constraint user_study_preferences_speech_rate_check check (speech_rate between 0.5 and 2)
);

create table if not exists public.user_word_notes (
  user_id uuid not null references auth.users(id) on delete cascade,
  vocab_word_id bigint not null references public.vocab_words(id) on delete cascade,
  note text not null default '',
  mnemonic text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, vocab_word_id),
  constraint user_word_notes_note_length check (length(note) <= 2000),
  constraint user_word_notes_mnemonic_length check (length(mnemonic) <= 2000)
);

create table if not exists public.vocab_passages (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  passage text not null,
  source_label text,
  source_url text,
  created_at timestamptz not null default now(),
  constraint vocab_passages_not_blank check (length(btrim(passage)) > 0)
);

create table if not exists public.vocab_passage_words (
  passage_id bigint not null references public.vocab_passages(id) on delete cascade,
  vocab_word_id bigint not null references public.vocab_words(id) on delete cascade,
  explanation text not null,
  primary key (passage_id, vocab_word_id),
  constraint vocab_passage_words_explanation_not_blank check (length(btrim(explanation)) > 0)
);

alter table public.user_word_mastery
  add column if not exists fsrs_due timestamptz,
  add column if not exists fsrs_stability double precision,
  add column if not exists fsrs_difficulty double precision,
  add column if not exists fsrs_elapsed_days integer not null default 0,
  add column if not exists fsrs_scheduled_days integer not null default 0,
  add column if not exists fsrs_reps integer not null default 0,
  add column if not exists fsrs_lapses integer not null default 0,
  add column if not exists fsrs_state smallint not null default 0,
  add column if not exists fsrs_last_review timestamptz,
  add column if not exists fsrs_version text not null default 'v1';

create index if not exists study_question_attempts_user_created_idx
  on public.study_question_attempts (user_id, created_at desc);
create index if not exists user_word_mastery_fsrs_due_idx
  on public.user_word_mastery (user_id, fsrs_due)
  where status <> 'known';
drop trigger if exists set_user_study_preferences_updated_at on public.user_study_preferences;
create trigger set_user_study_preferences_updated_at
before update on public.user_study_preferences
for each row execute function public.set_updated_at();

drop trigger if exists set_user_word_notes_updated_at on public.user_word_notes;
create trigger set_user_word_notes_updated_at
before update on public.user_word_notes
for each row execute function public.set_updated_at();

alter table public.user_study_preferences enable row level security;
alter table public.user_word_notes enable row level security;
alter table public.vocab_passages enable row level security;
alter table public.vocab_passage_words enable row level security;

create policy "Users manage own study preferences"
on public.user_study_preferences for all
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

create policy "Users manage own word notes"
on public.user_word_notes for all
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

create policy "Authenticated users read passages"
on public.vocab_passages for select to authenticated using (true);

create policy "Authenticated users read passage words"
on public.vocab_passage_words for select to authenticated using (true);

insert into storage.buckets (id, name, public)
values ('vocab-images', 'vocab-images', true)
on conflict (id) do update set public = excluded.public;

create policy "Public reads curated vocabulary images"
on storage.objects for select
using (bucket_id = 'vocab-images');

update public.vocab_words
set
  roots = array['candidus — white, pure'],
  etymology = 'From Latin candidus, describing something white or unhidden; the sense developed toward openness and honesty.',
  confusable_words = array['candor — the noun meaning frank honesty']
where word = 'candid';

update public.vocab_words
set
  prefixes = array['circum- — around'],
  roots = array['specere — to look'],
  etymology = 'From Latin circumspicere, “to look around,” suggesting careful attention before acting.',
  confusable_words = array['circumscribe — restrict within limits']
where word = 'circumspect';

update public.vocab_words
set
  roots = array['credere — to believe'],
  suffixes = array['-ous — characterized by'],
  etymology = 'From Latin credulus, “easily believing.”',
  confusable_words = array['credible — believable', 'incredulous — unwilling to believe']
where word = 'credulous';

update public.vocab_words
set
  prefixes = array['cor- — together'],
  roots = array['roborare — to strengthen'],
  etymology = 'From Latin corroborare, “to strengthen,” as evidence strengthens a claim.',
  confusable_words = array['collaborate — work together']
where word = 'corroborate';

update public.vocab_words
set
  prefixes = array['de- — down'],
  roots = array['niger — black'],
  etymology = 'From Latin denigrare, originally “to blacken,” later to damage someone’s reputation.',
  confusable_words = array['deprecate — express disapproval', 'depreciate — lose value']
where word = 'denigrate';

insert into public.vocab_passages (slug, passage, source_label)
values
  (
    'evidence-and-conjecture',
    'The first report was little more than conjecture. Only after two independent laboratories reproduced the result could the researchers corroborate the original claim.',
    'VocabSAT original'
  ),
  (
    'public-debate',
    'The speaker’s bombastic opening delighted the crowd, but her later claims lacked evidence. A more circumspect audience might have questioned whether confidence had replaced reasoning.',
    'VocabSAT original'
  )
on conflict (slug) do update
set passage = excluded.passage, source_label = excluded.source_label;

insert into public.vocab_passage_words (passage_id, vocab_word_id, explanation)
select p.id, w.id,
  case w.word
    when 'conjecture' then 'The claim begins as a guess based on incomplete evidence.'
    when 'corroborate' then 'Independent results confirm and strengthen the original claim.'
    when 'bombastic' then 'The opening is grand and overblown rather than substantive.'
    else 'The audience is described as insufficiently cautious.'
  end
from public.vocab_passages p
join public.vocab_words w on
  (p.slug = 'evidence-and-conjecture' and w.word in ('conjecture', 'corroborate'))
  or (p.slug = 'public-debate' and w.word in ('bombastic', 'circumspect'))
on conflict (passage_id, vocab_word_id) do update
set explanation = excluded.explanation;

create or replace function public.get_study_analytics(window_days integer default 30)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
  with filtered as (
    select
      a.*,
      sw.source,
      row_number() over (
        partition by a.session_id, a.vocab_word_id
        order by a.created_at
      ) as word_attempt_number
    from public.study_question_attempts a
    join public.study_session_words sw on sw.id = a.session_word_id
    where a.user_id = (select auth.uid())
      and (window_days = 0 or a.created_at >= now() - make_interval(days => window_days))
  ), by_type as (
    select
      question_type::text as question_type,
      count(*)::integer as attempts,
      count(*) filter (where is_correct)::integer as correct,
      count(*) filter (where confidence = 'guessed')::integer as unsure,
      count(*) filter (where timed_out)::integer as timed_out,
      percentile_cont(0.5) within group (order by response_time_ms)
        filter (where response_time_ms is not null) as median_response_time_ms
    from filtered
    group by question_type
  )
  select jsonb_build_object(
    'attempts', (select count(*) from filtered),
    'accuracy', coalesce((select avg(case when is_correct then 1.0 else 0.0 end) from filtered), 0),
    'activeTimeMs', coalesce((select sum(response_time_ms) from filtered), 0),
    'medianResponseTimeMs', (select percentile_cont(0.5) within group (order by response_time_ms) from filtered where response_time_ms is not null),
    'timeoutRate', coalesce((select avg(case when timed_out then 1.0 else 0.0 end) from filtered), 0),
    'reviewRetention', coalesce((select avg(case when is_correct then 1.0 else 0.0 end) from filtered where source = 'review' and word_attempt_number = 1), 0),
    'byQuestionType', coalesce((select jsonb_agg(to_jsonb(by_type) order by question_type) from by_type), '[]'::jsonb)
  );
$$;
